config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'
  resources :items do 
    resources :joint_card_items
  end
  resources :carts
  resources :devise
  resources :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    
    has_many :joint_card_items
    has_many :items,  through: :joint_card_items

    def total
        items.sum(&:price)
    end
end

app/models/item.rb
class Item < ApplicationRecord
    validates :title, :description, :price, :image_url, presence: true
    validates :title, length: { in: 5..90 }
    validates :description, length: { in: 20..500 }
    validates :price, numericality: { greater_than: 0 }

    has_many :jointcarditems 
    has_many :carts, through: :jointcarditems

    has_many :joinorderitems
    has_many :orders, through: :joinorderitems

end

app/models/join_order_item.rb
class JoinOrderItem < ApplicationRecord
    belongs_to :order 
    belongs_to :item
end

app/models/joint_card_item.rb
class JointCardItem < ApplicationRecord
    belongs_to :cart
    belongs_to :item
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :joinorderitems
    has_many :items, through: :joinorderitems

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
    #validates :first_name, presence: true
    #validates :last_name, presence: true 
    has_one :cart 
    has_many :orders

  after_create :cart_create

# A améliorer et vite !

after_create :cart_create
  
def cart_create
    Cart.create( user_id: self.id)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_cart
    private
    def set_cart
      @current_cart = Cart.find(session[:cart_id])
      rescue ActiveRecord::RecordNotFound
      @current_cart = Cart.create(user: current_user)
      session[:cart_id] = @current_cart.id
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
before_action :require_login
 
  
  def index

  end
  

  def show
    @cart = @current_cart

   
  end
 
 

  def destroy
    
    #@joint_card_item = JointCardItem.find(params[:id])
    #@joint_card_item.destroy
    redirect_to cart_path
  end

  private
  def require_login
    unless authenticate_user!
      flash[:error] = "You must be logged in to access this section"
      redirect_to new_login_url # halts request cycle
    end
  end
  

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
        @items = Item.all
     
    end
    def show
        @item = Item.find(params[:id])
        @items = Item.all
    end
    
end

app/controllers/joint_card_items_controller.rb
class JointCardItemsController < ApplicationController
    before_action :set_cart, only: [:create, :destroy]
    
    def index
@cart = params(session[:id])
@item = params(item[:id])

    end
    def show
        

    end
    
        def create
            # Find associated product and current cart
            chosen_item = Item.find(params[:item_id])
            @item = chosen_item
            current_cart = @current_cart
            @joint_card_item = JointCardItem.new
            @joint_card_item.cart = current_cart
            @joint_card_item.item = chosen_item
            if @joint_card_item.save
              redirect_to cart_path(current_cart)
            else
              redirect_to root_path
            end
        end
    
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def secret
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    before_action :authenticate_user!, only: [:show]
    
    def show
        @user = User.find(current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/joints_cards_items_helper.rb
module JointsCardsItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/carts/show.html.erb
<section class="page-header">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="content">
					<h1 class="page-name">Cart</h1>
					<ol class="breadcrumb">
						<li><a href="#">Home</a></li>
						<li class="active">cart</li>
					</ol>
				</div>
			</div>
		</div>
	</div>
</section>
<div class="page-wrapper">
  <div class="cart shopping">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="block">
            <div class="product-list">
              <form method="post">
                <table class="table">
                  <thead>
                    <tr>
                      <th class="">Item Name</th>
                      <th class="">Item Price</th>
                      <th class="">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                  <% @cart.joint_card_items.each do |cart_item|%>
                    <tr class="">
                      <td class="">
                        <div class="product-info">
                          <img width="80" src="images/shop/cart-1.jpg" alt="" />
                          <%= cart_item.item.title %></a>
                        </div>
                      </td>
                      <td class=""><%= cart_item.item.price %> </td>
                      <td class="">
                        <a href="<%= @joint_card_items %>" class="btn btn-danger" data-confirm="Êtes-vous sûr ?" data-method="DELETE">Supprimer</a>
                      </td>
                        
                    </tr>
                   
                    
                     <% end %>
                     <p>Prix du panier <%= @cart.total %></p>
                  </tbody>
                </table>
                <a href="checkout.html" class="btn btn-main pull-right">Checkout</a>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> 
<html class="no-js"> <!--<![endif]-->
<head>


  <title>ChatonsOnRails-commerce template</title>



</head>


<body id="body">

				

<section class="products section">
	<div class="container">

		<div class="row">
			<div class="title text-center">
				<h2>Nos photos de chatons super bg</h2>
			</div>
		</div>

<% @items.each do |item|%>
			<div class="col-md-4">
				<div class="product-item">
					<div class="product-thumb">

						 <img src="<%= item.image_url %>"> 




						<div class="preview-meta">
							<ul>
								<li>
									<%= button_to "Add to cart", item_joint_card_items_path(item.id), {method: :post, :class => "btn btn-lg btn-primary"} %>
								</li>
							</ul>
                      	</div>
					</div>
					<div class="product-content">
						<h4><a href="<%= item_path(item.id)%>"><%= item.title%></a></h4>
						<p class="price"><%= item.price%>€</p>
					</div>
				</div>
			</div>
			<% end %>
		
		
	</div>
</section>

  </body>
  </html>

app/views/items/show.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> 
<html class="no-js"> <!--<![endif]-->
<head>  <title>Aviato | E-commerce template</title>
</head>

<body id="body">
<section class="single-product">
	<div class="container">
		<div class="row mt-20">
			<div class="col-md-5">
				<div class="single-product-slider">
					<div id='carousel-custom' class='carousel slide' data-ride='carousel'>
						<div class='carousel-outer'>
							<!-- me art lab slider -->
							<div class='carousel-inner '>
								<div class='item active'>
                                <img class="img-responsive" src="<%= @item.image_url %>" alt="product-img">
								</div>
								
							</div>
	
						</div>
						
						
					</div>
				</div>
			</div>
			<div class="col-md-7">
				<div class="single-product-details">
					<h2><%= @item.title %></h2>
					<p class="product-price"><%= @item.price %>0 €</p>
					
					<p class="product-description mt-20">
                    <%= @item.description %>
					</p>
					
					
					<div class="product-quantity">
						<span>Quantity:</span>
						<div class="product-quantity-slider">
							<input id="product-quantity" type="text" value="1" name="product-quantity" disabled>
						</div>
					</div>
                    
                    <!--A MODIFIER REF DE MISE EN PANIER -->  
					
							
					<%= button_to "Add to cart", item_joint_card_items_path(@item.id), {method: :post, :class => "btn btn-lg btn-primary"} %>
				</div>
			</div>
		</div>
		
		
	</div>
</section>
<section class="products related-products section">
	<div class="container">
		<div class="row">
			<div class="title text-center">
				<h2>Related Products</h2>
			</div>
		</div>

		<% @items.each do |item|%>
			<div class="col">
				<div class="col-md-3">
					<div class="product-item">
						<div class="product-thumb">
							<img src="<%= item.image_url %>">
						</div>
						<div class="product-content">
							<h4><a href="<%= item_path(item.id)%>"><%= item.title%></a></h4>
							<p class="price"><%= item.price%>0 €</p>
							
						</div>
					</div>
				</div>
			</div>
		<% end %>
		
	</div>
</section>



<!-- Modal -->
<div class="modal product-modal fade" id="product-modal">
	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		<i class="tf-ion-close"></i>
	</button>
  	<div class="modal-dialog " role="document">
    	<div class="modal-content">
	      	<div class="modal-body">
	        	<div class="row">
	        		<div class="col-md-8">
	        			<div class="modal-image">
		        			<img class="img-responsive" src="images/shop/products/modal-product.jpg" />
	        			</div>
	        		</div>
	        		<div class="col-md-3">
	        			<div class="product-short-details">
	        				<h2 class="product-title">GM Pendant, Basalt Grey</h2>
	        				<p class="product-price">$200</p>
	        				<p class="product-short-description">
	        					Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem iusto nihil cum. Illo laborum numquam rem aut officia dicta cumque.
	        				</p>
	        				<a href="" class="btn btn-main">Add To Cart</a>
	        			</div>
	        		</div>
	        	</div>
	        </div>
    	</div>
  	</div>
</div>

  </body>
  </html>

app/views/joints_cards_items/new.html.erb
<h1> BIte <% redirect_to carts_path %> </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="description" content="Aviato E-Commerce Template">
  
  <meta name="author" content="Themefisher.com">
    <title>Chatonsonrails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<!-- Mobile Specific Meta-->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<!-- Favicon -->
	<link rel="shortcut icon" type="image/x-icon" href="img/favicon.png" />
	
	<!-- Themefisher Icon font -->
	<link rel="stylesheet" href="plugins/themefisher-font/style.css">
	<!-- bootstrap.min css -->
	<link rel="stylesheet" href="plugins/bootstrap/css/bootstrap.min.css">
	
	<!-- animate.css -->
	<link rel="stylesheet" href="plugins/animate-css/animate.css">
	
	<!-- Revolution Slider -->
	<link rel="stylesheet" type="text/css" href="plugins/revolution-slider/revolution/fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css">
	<link rel="stylesheet" type="text/css" href="plugins/revolution-slider/revolution/fonts/font-awesome/css/font-awesome.css">
  
	<!-- REVOLUTION STYLE SHEETS -->
	<link rel="stylesheet" type="text/css" href="plugins/revolution-slider/revolution/css/settings.css">
	<link rel="stylesheet" type="text/css" href="plugins/revolution-slider/revolution/css/layers.css">
	<link rel="stylesheet" type="text/css" href="plugins/revolution-slider/revolution/css/navigation.css">
	
	<!-- Main Stylesheet -->
	<link rel="stylesheet" href="css/style.css">
  </head>

  <body>
  	<!-- Start Top Header Bar -->
  	<section class="top-header">
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-xs-12 col-sm-4">
				
				</div>
				<div class="col-md-4 col-xs-12 col-sm-4">
					<!-- Site Logo -->
					<div class="logo text-center">
						<h1><a href="/"> BicraveDeChatons.com </a></h1>
					</div>
				</div>
				<!-- Log -->
				<div class="col-md-4 col-xs-12 col-sm-4">
					<ul class="top-menu text-right list-inline ">
 					<% if user_signed_in? %>
    					<li>
      					<%= link_to "Déconnection", destroy_user_session_path, method: :delete %>
    					</li>
    					<li>
     					<%= current_user.email %>
						</li>y 
						<li> 
						<%= link_to "Ton profil", user_path(current_user.id)%>
						</li>
						<li>
						<%= link_to "Edit ton profil", edit_user_registration_path %>
						</li>
						<!-- Cart -->
				
	         			<li class="dropdown cart-nav dropdown-slide">
	        	    		<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"><i class="tf-ion-android-cart"></i>Panier</a>
	         	   				<div class="dropdown-menu cart-dropdown">
	            					<!-- Cart Item -->
	            					<div class="media">
	            						<div class="media-body">
	            							<h4 class="media-heading"><a href="">A remplacer par le vrai panier</a></h4>
	            							<div class="cart-price">
                        	      				<span>1 x</span>
                         	     				<span>666.00</span>
                        	    			</div>
	            						</div>
                      					<a href="#" class="remove"><i class="tf-ion-close"></i></a>
	            					</div><!-- / Cart Item -->
	            					<!-- Cart Item -->
	            					<div class="media">
	            						<div class="media-body">
	            							<h4 class="media-heading"><a href="">A remplacer par le vrai panier</a></h4>
	            							<div class="cart-price">
                        						<span>1 x</span>
                              					<span>666</span>
                            				</div>
	            						</div>
                        				<a href="#" class="remove"><i class="tf-ion-close"></i></a>
	            					</div><!-- / Cart Item -->
	            					<div class="cart-summary">
                        				<span>Total</span>
                        				<span class="total-price">$1799.00</span>
                    				</div>
                    				<ul class="text-center cart-buttons">

                    					<li><a href="<%= carts_path%>" class="btn btn-small">Voir le panier</a></li>
										<li><a href="" class="btn btn-small btn-solid-border">Paiement</a></li>
										

                   					</ul>
                				</div>
	        				</li><!-- / Cart -->
  					<% else %>
    					<li>    
      					<%= link_to "Sign in", new_user_session_path %>
						</li>
						<li>
    					<%= link_to "Sign up", new_user_registration_path %>
    					</li>

					<% end %>
				
	        			</ul><!-- / .nav .navbar-nav .navbar-right -->
					</div>
				</div>
			</div>
		</section>
		<!-- End Top Header Bar -->
	<%= yield %>
	<footer class="footer section text-center">
	<div class="container">
		<div class="row">
				<p class="copyright-text">Copyright Team Toulouse 2019</p>
			</div>
		</div>
	</div>
</footer>
	<!--    Essential Scripts
    =====================================-->
    
    <!-- Main jQuery -->
    <script src="https://code.jquery.com/jquery-git.min.js"></script>
    <!-- Bootstrap 3.1 -->
    <script src="plugins/bootstrap/js/bootstrap.min.js"></script>
    <!-- Bootstrap Touchpin -->
    <script src="plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js"></script>
    <!-- Instagram Feed Js -->
    <script src="plugins/instafeed-js/instafeed.min.js"></script>
    <!-- Video Lightbox Plugin -->
    <script src="plugins/ekko-lightbox/dist/ekko-lightbox.min.js"></script>
    <!-- Count Down Js -->
    <script src="plugins/count-down/jquery.countdown.min.js"></script>
    
    <!-- Revolution Slider -->
    <script type="text/javascript" src="plugins/revolution-slider/revolution/js/jquery.themepunch.tools.min.js"></script>
    <script type="text/javascript" src="plugins/revolution-slider/revolution/js/jquery.themepunch.revolution.min.js"></script>
    
    <!-- Revolution Slider -->
    <script type="text/javascript" src="plugins/revolution-slider/revolution/js/extensions/revolution.extension.actions.min.js"></script>
    <script type="text/javascript" src="plugins/revolution-slider/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
    <script type="text/javascript" src="plugins/revolution-slider/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
    <script type="text/javascript" src="plugins/revolution-slider/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
    <script type="text/javascript" src="plugins/revolution-slider/revolution/js/extensions/revolution.extension.migration.min.js"></script>
    <script type="text/javascript" src="plugins/revolution-slider/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
    <script type="text/javascript" src="plugins/revolution-slider/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
    <script type="text/javascript" src="plugins/revolution-slider/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
    <script type="text/javascript" src="plugins/revolution-slider/revolution/js/extensions/revolution.extension.video.min.js"></script>
    <script type="text/javascript" src="plugins/revolution-slider/revolution/js/extensions/revolution.extension.video.min.js"></script>
    <script type="text/javascript" src="plugins/revolution-slider/assets/warning.js"></script>  



    <!-- Custom js -->
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBItRd4sQ_aXlQG_fvEzsxvuYyaWnJKETk&callback=initMap"></script>

    <script src="js/script.js"></script>
    
  </body>
</html>

app/views/static_pages/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/user/show.html.erb
<section class="user-dashboard page-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="dashboard-wrapper dashboard-user-profile">
          <div class="media">
            <div class="pull-left text-center" href="#">
              <img class="media-object user-img" src="https://i.pinimg.com/474x/2a/cb/22/2acb220cc8371146f441051e08791a72.jpg" alt="Image">
            </div>
            <div class="media-body">
              <ul class="user-profile-list">
                <li><span>First-Name:</span><%= @user.first_name %></li>
                <li><span>Last-name:</span><%= @user.last_name %></li>
                <li><span>Email:</span><%= @user.email %></li>
              </ul>
            </div>
		  <%= link_to edit_user_registration_path do %>
				<button type="button" class="btn btn-main text-center mt-4">Editer votre compte </button>
			<% end %>
                
             
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>